#!/usr/bin/python
"""
Problem 2
19 October 2001

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def fibonacci_generator(max):
	yield 1
	yield 2
	prev = [1,2]
	while True:
		nextSum = sum(prev)
		if nextSum > max:
			break
		prev = [prev[1], nextSum]
		yield nextSum

below_100 = [x for x in fibonacci_generator(4000000) if x % 2 == 0]

print sum(below_100)


